import { createFileRoute, Link } from "@tanstack/react-router";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/")({
  component: Landing,
});

function Landing() {
  const { user } = useAuth();
  return (
    <div className="min-h-screen bg-background">
      <header className="container-narrow flex items-center justify-between py-6">
        <Link to="/" className="font-display text-2xl font-semibold text-foreground">
          RoleCraft
        </Link>
        <nav className="flex items-center gap-2 text-sm">
          <Link to="/portfolios" className="rounded-lg px-3 py-2 text-muted-foreground hover:text-foreground">
            Browse portfolios
          </Link>
          <Link to="/recruiters" className="rounded-lg px-3 py-2 text-muted-foreground hover:text-foreground">
            For recruiters
          </Link>
          {user ? (
            <Link to="/dashboard" className="rounded-xl bg-primary px-4 py-2 font-medium text-primary-foreground hover:opacity-90">
              Dashboard
            </Link>
          ) : (
            <Link to="/auth" className="rounded-xl bg-primary px-4 py-2 font-medium text-primary-foreground hover:opacity-90">
              Sign in
            </Link>
          )}
        </nav>
      </header>

      <main className="container-narrow flex flex-col items-center pt-16 pb-24 text-center sm:pt-24">
        <span className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card px-4 py-1.5 text-xs font-medium text-muted-foreground">
          <span className="h-1.5 w-1.5 rounded-full bg-accent" />
          AI-generated, role-specific challenges
        </span>
        <h1 className="font-display text-5xl font-semibold leading-[1.05] text-foreground sm:text-7xl">
          RoleCraft
        </h1>
        <p className="mt-6 max-w-2xl font-display text-2xl text-muted-foreground sm:text-3xl">
          Real projects. Real skills. <span className="text-foreground">Real opportunities.</span>
        </p>
        <p className="mt-6 max-w-xl text-base text-muted-foreground">
          Pick a professional role, solve industry-relevant challenges generated by AI, and build a public
          portfolio companies search to hire from.
        </p>

        <div className="mt-10 flex flex-col items-center gap-3 sm:flex-row">
          <Link
            to="/auth"
            className="inline-flex w-full items-center justify-center rounded-xl bg-primary px-6 py-3 text-base font-medium text-primary-foreground shadow-sm transition hover:opacity-90 sm:w-auto"
          >
            Get Started →
          </Link>
          <Link
            to="/portfolios"
            className="inline-flex w-full items-center justify-center rounded-xl border border-border bg-card px-6 py-3 text-base font-medium text-foreground transition hover:bg-muted sm:w-auto"
          >
            Browse Portfolios
          </Link>
        </div>

        <div className="mt-24 grid w-full grid-cols-1 gap-4 sm:grid-cols-3">
          {[
            { emoji: "🎯", title: "Pick your role", body: "From PM to UX, choose what you're training for." },
            { emoji: "⚡", title: "Get AI projects", body: "Real-world challenges tailored to your level." },
            { emoji: "💼", title: "Get hired", body: "Your work becomes a portfolio recruiters search." },
          ].map((c) => (
            <div key={c.title} className="rounded-2xl border border-border bg-card p-6 text-left">
              <div className="text-3xl">{c.emoji}</div>
              <h3 className="mt-4 font-display text-xl font-semibold">{c.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{c.body}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className="container-narrow border-t border-border py-8 text-sm text-muted-foreground">
        © {new Date().getFullYear()} RoleCraft
      </footer>
    </div>
  );
}
